### ISSUE TITLE
Wrangler.toml not required?

### ISSUE THREAD

**Issue by pantharshit007** [Code42Cate/hackathon-starter#2]
hey, why is it that we don't need `wrangler.toml` in this setup and in the index.ts inside database where you are exporting the prisma client why are you creating prisma instance again and again.

why are we not doing something like this:

```typescript
const prismaClientSingleton = () => {
  return new PrismaClient();
};

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>;

declare global {
  var prismaGlobal: PrismaClientSingleton | undefined;
}

const db = globalThis.prismaGlobal ?? prismaClientSingleton();

// in order to avoid creating too many prisma instances in development.
if (process.env.NODE_ENV !== "production") {
  globalThis.prismaGlobal = db;
}
``` 

these are just my doubts do let me know if I am missing something here.

**Comment by Code42Cate** [comment]
Hi! wrangler is just cloudflare workers right? I dont use that here, so its not needed

And yes youre right, the database client is implemented wrong, this is very stupid. Thanks for bringig it up :D  

I'd appreciate if you can make a PR, otherwise I will do that in a few weeks when I got more time. Thanks!

**Comment by pantharshit007** [comment]
sure I will raise a pr for that and yeah hono is just a wrapper over Cloudflare workers for better experience and convinence.
